export enum MachineClass {
  DRILLING_MACHINE = 'DRILLING_MACHINE',
  GUNDRILL_MACHINE = 'GUNDRILL_MACHINE',
  MACHINING_CENTRE = 'MACHINING_CENTRE',
  MILLING_MACHINE = 'MILLING_MACHINE',
  MULTI_TASKING_MACHINE = 'MULTI_TASKING_MACHINE',
  TURNING_MACHINE = 'TURNING_MACHINE'
}
