export enum MachiningCapabilityProfile {
  BORING_CAPABILITY = 'BORING_CAPABILITY',
  DRILLING_CAPABILITY = 'DRILLING_CAPABILITY',
  GUNDRILL_CAPABILITY = 'GUNDRILL_CAPABILITY',
  MILLING_CAPABILITY = 'MILLING_CAPABILITY',
  TURNING_CAPABILITY = 'TURNING_CAPABILITY',
}
