export enum PalletStorageConfiguration {
  CAROUSEL = 'CAROUSEL',
  CAROUSEL_2_PLACE = 'CAROUSEL_2_PLACE',
  CHAIN = 'CHAIN',
  FIXED_2_PLACE = 'FIXED_2_PLACE',
  MULTI_STOREY = 'MULTI_STOREY',
  STRAIGHT_LINE = 'STRAIGHT_LINE',
}
